name: MacTask

on:
  push:
    paths:
    - '**.lua'

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    
    - name: LogAllEnv
      run: printenv
    
    - uses: actions/checkout@v1

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: '2.2.8'

    - name: BuildIOS
      run: sh ./BuildIOS.sh  
      
    - name: BuildMac
      run: sh ./BuildMac.sh  
      
    - name: CommitBinaries
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.email "imxqliu@live.com"
        git config user.name "$GITHUB_ACTOR"
        git checkout master
        sudo git pull origin master
        sudo git add build/iphoneos/*
        sudo git add build/macosx/*
        sudo git commit -m "[$GITHUB_WORKFLOW]Auto commit from Github Action"
        git remote set-url --push origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git push origin master
