name: WindowsTask

on:
  push:
    paths:
    - '**.lua'

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    
    - name: LogAllEnv
      run: set
      
    - uses: actions/checkout@v1
    

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: '2.2.8'
    
    - name: BuildWindows
      run: BuildWindows.bat
      
    - name: BuildAndroid
      run: BuildAndroid.bat
      
      
    - name: CommitBinaries
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.email "imxqliu@live.com"
        git config user.name "%GITHUB_ACTOR%"
        git checkout master
        git pull origin master
        git add build/windows/*
        git add build/android/*
        git commit -m "[%GITHUB_WORKFLOW%]Auto commit from Github Action"
        git remote set-url --push origin https://%GITHUB_ACTOR%:%GITHUB_TOKEN%@github.com/%GITHUB_REPOSITORY%
        git push origin master